replicaCount: 1

image:
  repository: ghcr.io/mibmo/mib.dev
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

ingress:
  hosts: []
  issuer:
    kind: ClusterIssuer
    name: scaleway-letsencrypt
