apiVersion: v1
kind: Service
metadata:
  name: client-api
spec:
  ports:
    - port: 7771
      name: client-api-internal
    - port: 8071
      name: client-api
  selector:
    app: client-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: client-api
  template:
    metadata:
      labels:
        app: client-api
    spec:
      volumes:
        - name: config
          configMap:
            name: dendrite-config
        - name: certificate
          secret:
            secretName: matrix-tls
            optional: false
        - name: matrix-key
          secret:
            secretName: matrix-key
            optional: false
      containers:
        - name: client-api
          image: docker.io/matrixdotorg/dendrite-polylith:latest
          args: ["clientapi"]
          volumeMounts:
            - name: config
              subPath: config.yaml
              mountPath: /etc/dendrite/dendrite.yaml
              readOnly: true
            - name: certificate
              subPath: tls.crt
              mountPath: /etc/dendrite/server.crt
              readOnly: true
            - name: certificate
              subPath: tls.key
              mountPath: /etc/dendrite/server.key
              readOnly: true
            - name: matrix-key
              subPath: private.key
              mountPath: /etc/dendrite/matrix_key.pem
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          # tcp liveness probe on api port
