resources:
  - server-certificate.yaml
  - matrix-private-key.yaml
  - old-matrix-keys.yaml
  - networking.yaml
  - well-known.yaml

  # Polylith components
  - appservice-api.yaml
  - client-api.yaml
  - federation-api.yaml
  - keyserver.yaml
  - media-api.yaml
  - roomserver.yaml
  - sync-api.yaml
  - user-api.yaml
  - mscs-database.yaml
configMapGenerator:
  - name: dendrite-config
    files:
      - config.yaml
  - name: well-known-config
    files:
      - well-known-nginx.conf

replicas:
  - name: appservice-api
    count: 3
  - name: client-api
    count: 3
  - name: federation-api
    count: 3
  - name: keyserver
    count: 3
  - name: media-api
    count: 3
  - name: roomserver
    count: 3
  - name: sync-api
    count: 3
  - name: user-api
    count: 3
