resources:
  - server-certificate.yaml
  - matrix-private-key.yaml
  - networking.yaml
  - well-known.yaml

  # Polylith components
  - appservice-api.yaml
  - client-api.yaml
  - federation-api.yaml
  - keyserver.yaml
  - media-api.yaml
  - roomserver.yaml
  - sync-api.yaml
  - user-api.yaml
configMapGenerator:
  - name: dendrite-config
    files:
      - config.yaml
  - name: well-known-files
    files:
      - well-known_client.json
      - well-known_server.json
