apiVersion: v1
kind: Service
metadata:
  name: media-api
spec:
  ports:
    - port: 7774
      name: media-api-internal
    - port: 8074
      name: media-api
  selector:
    app: media-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: media-api
  template:
    metadata:
      labels:
        app: media-api
    spec:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-store
        - name: config
          configMap:
            name: dendrite-config
        - name: certificate
          secret:
            secretName: matrix-tls
            optional: false
        - name: matrix-key
          secret:
            secretName: matrix-key
            optional: false
      containers:
        - name: media-api
          image: docker.io/matrixdotorg/dendrite-polylith:latest
          args: ["mediaapi"]
          volumeMounts:
            - name: media
              mountPath: /etc/dendrite/media_store/
            - name: config
              subPath: config.yaml
              mountPath: /etc/dendrite/dendrite.yaml
              readOnly: true
            - name: certificate
              subPath: tls.crt
              mountPath: /etc/dendrite/server.crt
              readOnly: true
            - name: certificate
              subPath: tls.key
              mountPath: /etc/dendrite/server.key
              readOnly: true
            - name: matrix-key
              subPath: private.key
              mountPath: /etc/dendrite/matrix_key.pem
              readOnly: true
          # tcp liveness probe on api port
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-store
spec:
  storageClassName: scw-bssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: media-api-database
  labels:
    app: media-api-database
spec:
  ports:
    - port: 5432
      name: database
  selector:
    app: media-api-database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: media-api-database
spec:
  selector:
    matchLabels:
      app: media-api-database
  serviceName: "media-api-database"
  replicas: 1
  template:
    metadata:
      labels:
        app: media-api-database
    spec:
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: media-api-database
      containers:
        - name: postgres
          image: docker.io/postgres:14.4-alpine
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: database
              mountPath: /var/lib/postgresql/data
          env:
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
            - name: POSTGRES_INITDB_ARGS
              value: "--locale=en_GB.UTF_8"
            - name: POSTGRES_DB
              value: "mediaapi"
            - name: POSTGRES_USER
              value: "mediaapi"
            - name: POSTGRES_PASSWORD
              value: "mediaapi" # use sealed secret
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - mediaapi
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-api-database
spec:
  storageClassName: scw-bssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
