apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: scaleway-secret
  namespace: cert-manager
spec:
  encryptedData:
    SCW_ACCESS_KEY: AgA/XAlwZwiF5bRb7WZhhkdj1Wof0lnwW48Dqc22gopkadsTXr9Z3F4YhQOzXFXFnPpmE2Dt3hAL/NY5qKnWpIGZkUcekTQiP+fKAIQzuAdZs2aAmLUFm1XpwIlvNfDXcelKq73/9vhWxykTrwkd9uZO+p76P7Fn+CM3fOBXGJbq/TVgiOvbtwyzM3tZcx9QoxkURBIowxXeaGrjFzfEJr8L4CPo2M4EvObaXZkMeM+58YsJpknPIGFihI2ns/0w1nesL+JLl7w394ecINmWBB5DAa+hLPlsPsBuFyfBXsC1jEu/TY17fUWF/2wBv9ut6if1madsTLBHz18sTp67rp7TFc/iVCjityLHP+2Dp6/pEg5rQ5vk30nx5AEhIPk7bA2nIIv3XnpOAgL3z2WXfT1QQk+R9lNz22JHNFcNNFZ2e2jBNGk36xyFPt7BNv/M3anqYzG4tHkohstfmFpivAHQ7Uwk453+cHWacwxIid11I02DsqKkGPLv4Ezp0l3DQZJDhrznbeLc2PmtCbUSf5t0MQg6yIz8tipiQcxKn8iMfAFx/6ETdMG0imwEwkLPqZQY8Br7MQYMSGki461ppOueoTDmBRO4xlgobB4VJaBv32XpMLkFr0C1ZxAaGGpZwU6Rwa+hQBUiSM1SxAzQgjFVf3afUo8FdW/b8Y+aAK8djz3CPr4b0R43ZcMimaMlIqIV8RpQ1gPwIpKHnI9Vf2/o1hJseQ==
    SCW_SECRET_KEY: AgA9b1sEtyXoqCwE5gk6HZYMtWexB9MPgwgdgiY9PNtABX0DRu3YRQt2PhocaQ/DZFwPPAcncUuenDCkTEgiRXCHqYMtU5zQnI91mEfR3wsyPBVjs68eDRwTQ+25Z1YAyos+XngN0zmchD48qggILnQSyasm1jJS9Xyr0yFEJZkzv1by0z3dsA81OkkBq8GXjCD13cUysOLu1+91U1xAL27VO0Yx6d/oPUhExirkDJBCCzZgP3b8JUYSy9QV8+VMaaQdGEHcPCUAXhaWee4D8UVBRLjnTnpkhjC9Usw3vTEKL36ACw3OBgMqE7fpsfeD8a1dt57qFjX4RX3Nlhvlwcb+9FXpkD91OhL2YPNDcgpoBmWM69LjkTygJVi+TVNeBkf2afMUUGtWYyLxehq5Tb8NVcB6R19wtUkMmfwKXJrX5A4xCSXrACbMDJusBoYa+kuKCWAZlfJinJvdSTqVko4KpGY0breYTg3TWE3lVap8oCC+IlGJ+dprA6BJXEAdtnI5uVQZ/j+t8S6+UWzxu4YNKCCvPV9X5ZARWdCVwqhZ9wnX5JBVakx3Hlw+ZBrTwnqxzrNYPIFotDSOCBITUp7ZKvC4pt+xrc4dso5hPb1NB4pydQqaOg2XbChdjORSF4pOZZypR8Y2Cq4Bk/dVLlbNrLPQKDMjU57a7C7KJBsOda/OUODk0tPydO0kXu5OnWCrkIucgf7zmTnBOnmX7AqRdzJSmN22cg4U23IkxJQ5cgoJpFI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: scaleway-secret
      namespace: cert-manager

