apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: scaleway-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mib@mib.dev
    privateKeySecretRef:
      name: scaleway-letsencrypt
    solvers:
      - dns01:
          webhook:
            groupName: acme.scaleway.com
            solverName: scaleway
            config:
              accessKeySecretRef:
                name: scaleway-secret
                key: SCW_ACCESS_KEY
              secretKeySecretRef:
                name: scaleway-secret
                key: SCW_SECRET_KEY
