apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: imageproxy
spec:
  issuerRef:
    kind: ClusterIssuer
    name: scaleway-letsencrypt
  secretName: imageproxy-tls
  dnsNames:
    - ip.mib.dev
