apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend
spec:
  issuerRef:
    kind: ClusterIssuer
    name: scaleway-letsencrypt
  secretName: frontend-tls
  dnsNames:
    - search.mib.dev
