apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mx-kanpai
spec:
  issuerRef:
    kind: ClusterIssuer
    name: scaleway-letsencrypt
  secretName: mx-kanpai-tls
  commonName: mx.kanp.ai
  dnsNames:
    - mx.kanp.ai
