apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "mibdev.fullname" . }}-cert
  namespace: istio-ingress
spec:
  issuerRef:
  {{- toYaml .Values.ingress.issuer | nindent 4 }}
  secretName: {{ include "mibdev.fullname" . }}-tls
  dnsNames:
  {{- range .Values.ingress.hosts }}
    - {{ . | quote }}
  {{- end }}
