apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mibdev.fullname" . }}
  labels:
    app: mibdev
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mibdev
  template:
    metadata:
      labels:
        app: mibdev
    spec:
      containers:
        - name: mibdev
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 30
            periodSeconds: 10
