apiVersion: v1
kind: Service
metadata:
  name: discord-bridge
  labels:
    app: discord-bridge
spec:
  ports:
    - port: 8483
      name: database
  selector:
    app: discord-bridge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bridge
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: discord-bridge
  template:
    metadata:
      labels:
        app: discord-bridge
    spec:
      volumes:
        - name: config
          configMap:
            name: discord-bridge-config
        - name: registration
          secret:
            secretName: discord-bridge-registration
            optional: false
      containers:
        - name: mx-puppet-discord
          image: registry.gitlab.com/mx-puppet/discord/mx-puppet-discord:latest
          ports:
            - containerPort: 8483
              name: bridge
          volumeMounts:
            - name: config
              subPath: config.yaml
              mountPath: /data/config.yaml
            - name: registration
              subPath: discord-registration.yaml
              mountPath: /data/registration.yaml
          env:
            - name: CONFIG_PATH
              value: "/data/config.yaml"
            - name: REGISTRATION_PATH
              value: "/data/registration.yaml"
