apiVersion: v1
kind: Service
metadata:
  name: discord-bridge-database
  labels:
    app: discord-bridge-database
spec:
  ports:
    - port: 5432
      name: database
  selector:
    app: discord-bridge-database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discord-bridge-database
spec:
  selector:
    matchLabels:
      app: discord-bridge-database
  serviceName: "discord-bridge-database"
  replicas: 1
  template:
    metadata:
      labels:
        app: discord-bridge-database
    spec:
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: discord-bridge-database
      containers:
        - name: postgres
          image: docker.io/postgres:14.4-alpine
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: database
              mountPath: /var/lib/postgresql/data
          env:
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
            - name: POSTGRES_DB
              value: "discord"
            - name: POSTGRES_USER
              value: "discord"
            - name: POSTGRES_PASSWORD
              value: "discord" # use sealed secret
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - discord
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discord-bridge-database
spec:
  storageClassName: scw-bssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
