apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kanban
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:kanpai/infra.git
    targetRevision: dev
    path: wekan
    helm:
      values: |
        mongodb:
          storageClass: "scw-bssd"
          storageRequest: "1Gi"
        wekan:
          rootUrl: "https://kanban.kanp.ai"
        ingress:
          hosts:
            - "kanban.kanp.ai"
            - "wekan.kanp.ai"
  destination:
    name: in-cluster
    namespace: wekan
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
