apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mibdev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:kanpai/infra.git
    targetRevision: dev
    path: mibdev
    helm:
      parameters:
        - name: ingress.hosts[0]
          value: "mib.dev"
  destination:
    name: in-cluster
    namespace: mibdev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
