apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  sourceRepos:
    - 'https://grafana.github.io/helm-charts'
    - 'https://prometheus-community.github.io/helm-charts'
  destinations:
    - namespace: 'monitoring'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
